// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/v1/datastore.proto

// Protobuf Java Version: 3.25.3
package com.google.datastore.v1;

public interface ReserveIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.ReserveIdsResponse)
    com.google.protobuf.MessageOrBuilder {
}
