// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/query.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface AggregationQueryOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.AggregationQuery)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Nested query for aggregation
   * </pre>
   *
   * <code>.google.datastore.v1.Query nested_query = 1;</code>
   *
   * @return Whether the nestedQuery field is set.
   */
  boolean hasNestedQuery();

  /**
   *
   *
   * <pre>
   * Nested query for aggregation
   * </pre>
   *
   * <code>.google.datastore.v1.Query nested_query = 1;</code>
   *
   * @return The nestedQuery.
   */
  com.google.datastore.v1.Query getNestedQuery();

  /**
   *
   *
   * <pre>
   * Nested query for aggregation
   * </pre>
   *
   * <code>.google.datastore.v1.Query nested_query = 1;</code>
   */
  com.google.datastore.v1.QueryOrBuilder getNestedQueryOrBuilder();

  /**
   *
   *
   * <pre>
   * Optional. Series of aggregations to apply over the results of the
   * `nested_query`.
   *
   * Requires:
   *
   * * A minimum of one and maximum of five aggregations per query.
   * </pre>
   *
   * <code>
   * repeated .google.datastore.v1.AggregationQuery.Aggregation aggregations = 3 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  java.util.List<com.google.datastore.v1.AggregationQuery.Aggregation> getAggregationsList();

  /**
   *
   *
   * <pre>
   * Optional. Series of aggregations to apply over the results of the
   * `nested_query`.
   *
   * Requires:
   *
   * * A minimum of one and maximum of five aggregations per query.
   * </pre>
   *
   * <code>
   * repeated .google.datastore.v1.AggregationQuery.Aggregation aggregations = 3 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  com.google.datastore.v1.AggregationQuery.Aggregation getAggregations(int index);

  /**
   *
   *
   * <pre>
   * Optional. Series of aggregations to apply over the results of the
   * `nested_query`.
   *
   * Requires:
   *
   * * A minimum of one and maximum of five aggregations per query.
   * </pre>
   *
   * <code>
   * repeated .google.datastore.v1.AggregationQuery.Aggregation aggregations = 3 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  int getAggregationsCount();

  /**
   *
   *
   * <pre>
   * Optional. Series of aggregations to apply over the results of the
   * `nested_query`.
   *
   * Requires:
   *
   * * A minimum of one and maximum of five aggregations per query.
   * </pre>
   *
   * <code>
   * repeated .google.datastore.v1.AggregationQuery.Aggregation aggregations = 3 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  java.util.List<? extends com.google.datastore.v1.AggregationQuery.AggregationOrBuilder>
      getAggregationsOrBuilderList();

  /**
   *
   *
   * <pre>
   * Optional. Series of aggregations to apply over the results of the
   * `nested_query`.
   *
   * Requires:
   *
   * * A minimum of one and maximum of five aggregations per query.
   * </pre>
   *
   * <code>
   * repeated .google.datastore.v1.AggregationQuery.Aggregation aggregations = 3 [(.google.api.field_behavior) = OPTIONAL];
   * </code>
   */
  com.google.datastore.v1.AggregationQuery.AggregationOrBuilder getAggregationsOrBuilder(int index);

  com.google.datastore.v1.AggregationQuery.QueryTypeCase getQueryTypeCase();
}
