// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/query_profile.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface ExplainMetricsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.ExplainMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Planning phase information for the query.
   * </pre>
   *
   * <code>.google.datastore.v1.PlanSummary plan_summary = 1;</code>
   *
   * @return Whether the planSummary field is set.
   */
  boolean hasPlanSummary();

  /**
   *
   *
   * <pre>
   * Planning phase information for the query.
   * </pre>
   *
   * <code>.google.datastore.v1.PlanSummary plan_summary = 1;</code>
   *
   * @return The planSummary.
   */
  com.google.datastore.v1.PlanSummary getPlanSummary();

  /**
   *
   *
   * <pre>
   * Planning phase information for the query.
   * </pre>
   *
   * <code>.google.datastore.v1.PlanSummary plan_summary = 1;</code>
   */
  com.google.datastore.v1.PlanSummaryOrBuilder getPlanSummaryOrBuilder();

  /**
   *
   *
   * <pre>
   * Aggregated stats from the execution of the query. Only present when
   * [ExplainOptions.analyze][google.datastore.v1.ExplainOptions.analyze] is set
   * to true.
   * </pre>
   *
   * <code>.google.datastore.v1.ExecutionStats execution_stats = 2;</code>
   *
   * @return Whether the executionStats field is set.
   */
  boolean hasExecutionStats();

  /**
   *
   *
   * <pre>
   * Aggregated stats from the execution of the query. Only present when
   * [ExplainOptions.analyze][google.datastore.v1.ExplainOptions.analyze] is set
   * to true.
   * </pre>
   *
   * <code>.google.datastore.v1.ExecutionStats execution_stats = 2;</code>
   *
   * @return The executionStats.
   */
  com.google.datastore.v1.ExecutionStats getExecutionStats();

  /**
   *
   *
   * <pre>
   * Aggregated stats from the execution of the query. Only present when
   * [ExplainOptions.analyze][google.datastore.v1.ExplainOptions.analyze] is set
   * to true.
   * </pre>
   *
   * <code>.google.datastore.v1.ExecutionStats execution_stats = 2;</code>
   */
  com.google.datastore.v1.ExecutionStatsOrBuilder getExecutionStatsOrBuilder();
}
