// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/query.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface GqlQueryParameterOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.GqlQueryParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * A value parameter.
   * </pre>
   *
   * <code>.google.datastore.v1.Value value = 2;</code>
   *
   * @return Whether the value field is set.
   */
  boolean hasValue();

  /**
   *
   *
   * <pre>
   * A value parameter.
   * </pre>
   *
   * <code>.google.datastore.v1.Value value = 2;</code>
   *
   * @return The value.
   */
  com.google.datastore.v1.Value getValue();

  /**
   *
   *
   * <pre>
   * A value parameter.
   * </pre>
   *
   * <code>.google.datastore.v1.Value value = 2;</code>
   */
  com.google.datastore.v1.ValueOrBuilder getValueOrBuilder();

  /**
   *
   *
   * <pre>
   * A query cursor. Query cursors are returned in query
   * result batches.
   * </pre>
   *
   * <code>bytes cursor = 3;</code>
   *
   * @return Whether the cursor field is set.
   */
  boolean hasCursor();

  /**
   *
   *
   * <pre>
   * A query cursor. Query cursors are returned in query
   * result batches.
   * </pre>
   *
   * <code>bytes cursor = 3;</code>
   *
   * @return The cursor.
   */
  com.google.protobuf.ByteString getCursor();

  com.google.datastore.v1.GqlQueryParameter.ParameterTypeCase getParameterTypeCase();
}
