// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/entity.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface PartitionIdOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.PartitionId)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The ID of the project to which the entities belong.
   * </pre>
   *
   * <code>string project_id = 2;</code>
   *
   * @return The projectId.
   */
  java.lang.String getProjectId();

  /**
   *
   *
   * <pre>
   * The ID of the project to which the entities belong.
   * </pre>
   *
   * <code>string project_id = 2;</code>
   *
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString getProjectIdBytes();

  /**
   *
   *
   * <pre>
   * If not empty, the ID of the database to which the entities
   * belong.
   * </pre>
   *
   * <code>string database_id = 3;</code>
   *
   * @return The databaseId.
   */
  java.lang.String getDatabaseId();

  /**
   *
   *
   * <pre>
   * If not empty, the ID of the database to which the entities
   * belong.
   * </pre>
   *
   * <code>string database_id = 3;</code>
   *
   * @return The bytes for databaseId.
   */
  com.google.protobuf.ByteString getDatabaseIdBytes();

  /**
   *
   *
   * <pre>
   * If not empty, the ID of the namespace to which the entities belong.
   * </pre>
   *
   * <code>string namespace_id = 4;</code>
   *
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();

  /**
   *
   *
   * <pre>
   * If not empty, the ID of the namespace to which the entities belong.
   * </pre>
   *
   * <code>string namespace_id = 4;</code>
   *
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString getNamespaceIdBytes();
}
