// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/query.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface ProjectionOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.Projection)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The property to project.
   * </pre>
   *
   * <code>.google.datastore.v1.PropertyReference property = 1;</code>
   *
   * @return Whether the property field is set.
   */
  boolean hasProperty();

  /**
   *
   *
   * <pre>
   * The property to project.
   * </pre>
   *
   * <code>.google.datastore.v1.PropertyReference property = 1;</code>
   *
   * @return The property.
   */
  com.google.datastore.v1.PropertyReference getProperty();

  /**
   *
   *
   * <pre>
   * The property to project.
   * </pre>
   *
   * <code>.google.datastore.v1.PropertyReference property = 1;</code>
   */
  com.google.datastore.v1.PropertyReferenceOrBuilder getPropertyOrBuilder();
}
