// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/query.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface PropertyReferenceOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.PropertyReference)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * A reference to a property.
   *
   * Requires:
   *
   * * MUST be a dot-delimited (`.`) string of segments, where each segment
   * conforms to [entity property name][google.datastore.v1.Entity.properties]
   * limitations.
   * </pre>
   *
   * <code>string name = 2;</code>
   *
   * @return The name.
   */
  java.lang.String getName();

  /**
   *
   *
   * <pre>
   * A reference to a property.
   *
   * Requires:
   *
   * * MUST be a dot-delimited (`.`) string of segments, where each segment
   * conforms to [entity property name][google.datastore.v1.Entity.properties]
   * limitations.
   * </pre>
   *
   * <code>string name = 2;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();
}
