// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/datastore.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface ReserveIdsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.ReserveIdsResponse)
    com.google.protobuf.MessageOrBuilder {}
