// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/v1/datastore.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.v1;

@com.google.protobuf.Generated
public interface TransactionOptionsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.v1.TransactionOptions)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The transaction should allow both reads and writes.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadWrite read_write = 1;</code>
   *
   * @return Whether the readWrite field is set.
   */
  boolean hasReadWrite();

  /**
   *
   *
   * <pre>
   * The transaction should allow both reads and writes.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadWrite read_write = 1;</code>
   *
   * @return The readWrite.
   */
  com.google.datastore.v1.TransactionOptions.ReadWrite getReadWrite();

  /**
   *
   *
   * <pre>
   * The transaction should allow both reads and writes.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadWrite read_write = 1;</code>
   */
  com.google.datastore.v1.TransactionOptions.ReadWriteOrBuilder getReadWriteOrBuilder();

  /**
   *
   *
   * <pre>
   * The transaction should only allow reads.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadOnly read_only = 2;</code>
   *
   * @return Whether the readOnly field is set.
   */
  boolean hasReadOnly();

  /**
   *
   *
   * <pre>
   * The transaction should only allow reads.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadOnly read_only = 2;</code>
   *
   * @return The readOnly.
   */
  com.google.datastore.v1.TransactionOptions.ReadOnly getReadOnly();

  /**
   *
   *
   * <pre>
   * The transaction should only allow reads.
   * </pre>
   *
   * <code>.google.datastore.v1.TransactionOptions.ReadOnly read_only = 2;</code>
   */
  com.google.datastore.v1.TransactionOptions.ReadOnlyOrBuilder getReadOnlyOrBuilder();

  com.google.datastore.v1.TransactionOptions.ModeCase getModeCase();
}
