// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/admin/v1/datastore_admin.proto

package com.google.datastore.admin.v1;

public interface CreateIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.admin.v1.CreateIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Project ID against which to make the request.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <pre>
   * Project ID against which to make the request.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <pre>
   * The index to create. The name and state fields are output only and will be
   * ignored. Single property indexes cannot be created or deleted.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.Index index = 3;</code>
   * @return Whether the index field is set.
   */
  boolean hasIndex();
  /**
   * <pre>
   * The index to create. The name and state fields are output only and will be
   * ignored. Single property indexes cannot be created or deleted.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.Index index = 3;</code>
   * @return The index.
   */
  com.google.datastore.admin.v1.Index getIndex();
  /**
   * <pre>
   * The index to create. The name and state fields are output only and will be
   * ignored. Single property indexes cannot be created or deleted.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.Index index = 3;</code>
   */
  com.google.datastore.admin.v1.IndexOrBuilder getIndexOrBuilder();
}
