// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/admin/v1/datastore_admin.proto

package com.google.datastore.admin.v1;

public interface DatastoreFirestoreMigrationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.admin.v1.DatastoreFirestoreMigrationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The current state of migration from Cloud Datastore to Cloud Firestore in
   * Datastore mode.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationState migration_state = 1;</code>
   * @return The enum numeric value on the wire for migrationState.
   */
  int getMigrationStateValue();
  /**
   * <pre>
   * The current state of migration from Cloud Datastore to Cloud Firestore in
   * Datastore mode.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationState migration_state = 1;</code>
   * @return The migrationState.
   */
  com.google.datastore.admin.v1.MigrationState getMigrationState();

  /**
   * <pre>
   * The current step of migration from Cloud Datastore to Cloud Firestore in
   * Datastore mode.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationStep migration_step = 2;</code>
   * @return The enum numeric value on the wire for migrationStep.
   */
  int getMigrationStepValue();
  /**
   * <pre>
   * The current step of migration from Cloud Datastore to Cloud Firestore in
   * Datastore mode.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationStep migration_step = 2;</code>
   * @return The migrationStep.
   */
  com.google.datastore.admin.v1.MigrationStep getMigrationStep();
}
