// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/admin/v1/datastore_admin.proto

package com.google.datastore.admin.v1;

public interface DeleteIndexRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.admin.v1.DeleteIndexRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Project ID against which to make the request.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   * @return The projectId.
   */
  java.lang.String getProjectId();
  /**
   * <pre>
   * Project ID against which to make the request.
   * </pre>
   *
   * <code>string project_id = 1;</code>
   * @return The bytes for projectId.
   */
  com.google.protobuf.ByteString
      getProjectIdBytes();

  /**
   * <pre>
   * The resource ID of the index to delete.
   * </pre>
   *
   * <code>string index_id = 3;</code>
   * @return The indexId.
   */
  java.lang.String getIndexId();
  /**
   * <pre>
   * The resource ID of the index to delete.
   * </pre>
   *
   * <code>string index_id = 3;</code>
   * @return The bytes for indexId.
   */
  com.google.protobuf.ByteString
      getIndexIdBytes();
}
