// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/admin/v1/datastore_admin.proto

package com.google.datastore.admin.v1;

public interface ExportEntitiesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.datastore.admin.v1.ExportEntitiesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Location of the output metadata file. This can be used to begin an import
   * into Cloud Datastore (this project or another project). See
   * [google.datastore.admin.v1.ImportEntitiesRequest.input_url][google.datastore.admin.v1.ImportEntitiesRequest.input_url].
   * Only present if the operation completed successfully.
   * </pre>
   *
   * <code>string output_url = 1;</code>
   * @return The outputUrl.
   */
  java.lang.String getOutputUrl();
  /**
   * <pre>
   * Location of the output metadata file. This can be used to begin an import
   * into Cloud Datastore (this project or another project). See
   * [google.datastore.admin.v1.ImportEntitiesRequest.input_url][google.datastore.admin.v1.ImportEntitiesRequest.input_url].
   * Only present if the operation completed successfully.
   * </pre>
   *
   * <code>string output_url = 1;</code>
   * @return The bytes for outputUrl.
   */
  com.google.protobuf.ByteString
      getOutputUrlBytes();
}
