/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/datastore/admin/v1/datastore_admin.proto

package com.google.datastore.admin.v1;

public final class DatastoreAdminProto {
  private DatastoreAdminProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_CommonMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_CommonMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_CommonMetadata_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_CommonMetadata_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_Progress_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_Progress_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ExportEntitiesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ExportEntitiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ExportEntitiesRequest_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ExportEntitiesRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ImportEntitiesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ImportEntitiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ImportEntitiesRequest_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ImportEntitiesRequest_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ExportEntitiesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ExportEntitiesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ExportEntitiesMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ExportEntitiesMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ImportEntitiesMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ImportEntitiesMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_EntityFilter_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_EntityFilter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_GetIndexRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_GetIndexRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ListIndexesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ListIndexesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_ListIndexesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_ListIndexesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_datastore_admin_v1_IndexOperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_datastore_admin_v1_IndexOperationMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n/google/datastore/admin/v1/datastore_ad"
          + "min.proto\022\031google.datastore.admin.v1\032\034go"
          + "ogle/api/annotations.proto\032\027google/api/c"
          + "lient.proto\032\037google/api/field_behavior.p"
          + "roto\032%google/datastore/admin/v1/index.pr"
          + "oto\032#google/longrunning/operations.proto"
          + "\032\037google/protobuf/timestamp.proto\"\364\003\n\016Co"
          + "mmonMetadata\022.\n\nstart_time\030\001 \001(\0132\032.googl"
          + "e.protobuf.Timestamp\022,\n\010end_time\030\002 \001(\0132\032"
          + ".google.protobuf.Timestamp\022@\n\016operation_"
          + "type\030\003 \001(\0162(.google.datastore.admin.v1.O"
          + "perationType\022E\n\006labels\030\004 \003(\01325.google.da"
          + "tastore.admin.v1.CommonMetadata.LabelsEn"
          + "try\022>\n\005state\030\005 \001(\0162/.google.datastore.ad"
          + "min.v1.CommonMetadata.State\032-\n\013LabelsEnt"
          + "ry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\213\001\n\005S"
          + "tate\022\025\n\021STATE_UNSPECIFIED\020\000\022\020\n\014INITIALIZ"
          + "ING\020\001\022\016\n\nPROCESSING\020\002\022\016\n\nCANCELLING\020\003\022\016\n"
          + "\nFINALIZING\020\004\022\016\n\nSUCCESSFUL\020\005\022\n\n\006FAILED\020"
          + "\006\022\r\n\tCANCELLED\020\007\":\n\010Progress\022\026\n\016work_com"
          + "pleted\030\001 \001(\003\022\026\n\016work_estimated\030\002 \001(\003\"\215\002\n"
          + "\025ExportEntitiesRequest\022\027\n\nproject_id\030\001 \001"
          + "(\tB\003\340A\002\022L\n\006labels\030\002 \003(\0132<.google.datasto"
          + "re.admin.v1.ExportEntitiesRequest.Labels"
          + "Entry\022>\n\rentity_filter\030\003 \001(\0132\'.google.da"
          + "tastore.admin.v1.EntityFilter\022\036\n\021output_"
          + "url_prefix\030\004 \001(\tB\003\340A\002\032-\n\013LabelsEntry\022\013\n\003"
          + "key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\205\002\n\025ImportE"
          + "ntitiesRequest\022\027\n\nproject_id\030\001 \001(\tB\003\340A\002\022"
          + "L\n\006labels\030\002 \003(\0132<.google.datastore.admin"
          + ".v1.ImportEntitiesRequest.LabelsEntry\022\026\n"
          + "\tinput_url\030\003 \001(\tB\003\340A\002\022>\n\rentity_filter\030\004"
          + " \001(\0132\'.google.datastore.admin.v1.EntityF"
          + "ilter\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005val"
          + "ue\030\002 \001(\t:\0028\001\",\n\026ExportEntitiesResponse\022\022"
          + "\n\noutput_url\030\001 \001(\t\"\253\002\n\026ExportEntitiesMet"
          + "adata\0229\n\006common\030\001 \001(\0132).google.datastore"
          + ".admin.v1.CommonMetadata\022>\n\021progress_ent"
          + "ities\030\002 \001(\0132#.google.datastore.admin.v1."
          + "Progress\022;\n\016progress_bytes\030\003 \001(\0132#.googl"
          + "e.datastore.admin.v1.Progress\022>\n\rentity_"
          + "filter\030\004 \001(\0132\'.google.datastore.admin.v1"
          + ".EntityFilter\022\031\n\021output_url_prefix\030\005 \001(\t"
          + "\"\243\002\n\026ImportEntitiesMetadata\0229\n\006common\030\001 "
          + "\001(\0132).google.datastore.admin.v1.CommonMe"
          + "tadata\022>\n\021progress_entities\030\002 \001(\0132#.goog"
          + "le.datastore.admin.v1.Progress\022;\n\016progre"
          + "ss_bytes\030\003 \001(\0132#.google.datastore.admin."
          + "v1.Progress\022>\n\rentity_filter\030\004 \001(\0132\'.goo"
          + "gle.datastore.admin.v1.EntityFilter\022\021\n\ti"
          + "nput_url\030\005 \001(\t\"4\n\014EntityFilter\022\r\n\005kinds\030"
          + "\001 \003(\t\022\025\n\rnamespace_ids\030\002 \003(\t\"7\n\017GetIndex"
          + "Request\022\022\n\nproject_id\030\001 \001(\t\022\020\n\010index_id\030"
          + "\003 \001(\t\"_\n\022ListIndexesRequest\022\022\n\nproject_i"
          + "d\030\001 \001(\t\022\016\n\006filter\030\003 \001(\t\022\021\n\tpage_size\030\004 \001"
          + "(\005\022\022\n\npage_token\030\005 \001(\t\"a\n\023ListIndexesRes"
          + "ponse\0221\n\007indexes\030\001 \003(\0132 .google.datastor"
          + "e.admin.v1.Index\022\027\n\017next_page_token\030\002 \001("
          + "\t\"\245\001\n\026IndexOperationMetadata\0229\n\006common\030\001"
          + " \001(\0132).google.datastore.admin.v1.CommonM"
          + "etadata\022>\n\021progress_entities\030\002 \001(\0132#.goo"
          + "gle.datastore.admin.v1.Progress\022\020\n\010index"
          + "_id\030\003 \001(\t*}\n\rOperationType\022\036\n\032OPERATION_"
          + "TYPE_UNSPECIFIED\020\000\022\023\n\017EXPORT_ENTITIES\020\001\022"
          + "\023\n\017IMPORT_ENTITIES\020\002\022\020\n\014CREATE_INDEX\020\003\022\020"
          + "\n\014DELETE_INDEX\020\0042\234\007\n\016DatastoreAdmin\022\366\001\n\016"
          + "ExportEntities\0220.google.datastore.admin."
          + "v1.ExportEntitiesRequest\032\035.google.longru"
          + "nning.Operation\"\222\001\202\323\344\223\002%\" /v1/projects/{"
          + "project_id}:export:\001*\332A1project_id,label"
          + "s,entity_filter,output_url_prefix\312A0\n\026Ex"
          + "portEntitiesResponse\022\026ExportEntitiesMeta"
          + "data\022\355\001\n\016ImportEntities\0220.google.datasto"
          + "re.admin.v1.ImportEntitiesRequest\032\035.goog"
          + "le.longrunning.Operation\"\211\001\202\323\344\223\002%\" /v1/p"
          + "rojects/{project_id}:import:\001*\332A)project"
          + "_id,labels,input_url,entity_filter\312A/\n\025g"
          + "oogle.protobuf.Empty\022\026ImportEntitiesMeta"
          + "data\022\216\001\n\010GetIndex\022*.google.datastore.adm"
          + "in.v1.GetIndexRequest\032 .google.datastore"
          + ".admin.v1.Index\"4\202\323\344\223\002.\022,/v1/projects/{p"
          + "roject_id}/indexes/{index_id}\022\227\001\n\013ListIn"
          + "dexes\022-.google.datastore.admin.v1.ListIn"
          + "dexesRequest\032..google.datastore.admin.v1"
          + ".ListIndexesResponse\")\202\323\344\223\002#\022!/v1/projec"
          + "ts/{project_id}/indexes\032v\312A\030datastore.go"
          + "ogleapis.com\322AXhttps://www.googleapis.co"
          + "m/auth/cloud-platform,https://www.google"
          + "apis.com/auth/datastoreB\230\001\n\035com.google.d"
          + "atastore.admin.v1B\023DatastoreAdminProtoP\001"
          + "Z>google.golang.org/genproto/googleapis/"
          + "datastore/admin/v1;admin\252\002\037Google.Cloud."
          + "Datastore.Admin.V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.datastore.admin.v1.IndexProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_datastore_admin_v1_CommonMetadata_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_datastore_admin_v1_CommonMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_CommonMetadata_descriptor,
            new java.lang.String[] {
              "StartTime", "EndTime", "OperationType", "Labels", "State",
            });
    internal_static_google_datastore_admin_v1_CommonMetadata_LabelsEntry_descriptor =
        internal_static_google_datastore_admin_v1_CommonMetadata_descriptor.getNestedTypes().get(0);
    internal_static_google_datastore_admin_v1_CommonMetadata_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_CommonMetadata_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_datastore_admin_v1_Progress_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_datastore_admin_v1_Progress_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_Progress_descriptor,
            new java.lang.String[] {
              "WorkCompleted", "WorkEstimated",
            });
    internal_static_google_datastore_admin_v1_ExportEntitiesRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_datastore_admin_v1_ExportEntitiesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ExportEntitiesRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Labels", "EntityFilter", "OutputUrlPrefix",
            });
    internal_static_google_datastore_admin_v1_ExportEntitiesRequest_LabelsEntry_descriptor =
        internal_static_google_datastore_admin_v1_ExportEntitiesRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_datastore_admin_v1_ExportEntitiesRequest_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ExportEntitiesRequest_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_datastore_admin_v1_ImportEntitiesRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_datastore_admin_v1_ImportEntitiesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ImportEntitiesRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Labels", "InputUrl", "EntityFilter",
            });
    internal_static_google_datastore_admin_v1_ImportEntitiesRequest_LabelsEntry_descriptor =
        internal_static_google_datastore_admin_v1_ImportEntitiesRequest_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_datastore_admin_v1_ImportEntitiesRequest_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ImportEntitiesRequest_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_datastore_admin_v1_ExportEntitiesResponse_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_datastore_admin_v1_ExportEntitiesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ExportEntitiesResponse_descriptor,
            new java.lang.String[] {
              "OutputUrl",
            });
    internal_static_google_datastore_admin_v1_ExportEntitiesMetadata_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_datastore_admin_v1_ExportEntitiesMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ExportEntitiesMetadata_descriptor,
            new java.lang.String[] {
              "Common", "ProgressEntities", "ProgressBytes", "EntityFilter", "OutputUrlPrefix",
            });
    internal_static_google_datastore_admin_v1_ImportEntitiesMetadata_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_datastore_admin_v1_ImportEntitiesMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ImportEntitiesMetadata_descriptor,
            new java.lang.String[] {
              "Common", "ProgressEntities", "ProgressBytes", "EntityFilter", "InputUrl",
            });
    internal_static_google_datastore_admin_v1_EntityFilter_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_datastore_admin_v1_EntityFilter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_EntityFilter_descriptor,
            new java.lang.String[] {
              "Kinds", "NamespaceIds",
            });
    internal_static_google_datastore_admin_v1_GetIndexRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_datastore_admin_v1_GetIndexRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_GetIndexRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "IndexId",
            });
    internal_static_google_datastore_admin_v1_ListIndexesRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_datastore_admin_v1_ListIndexesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ListIndexesRequest_descriptor,
            new java.lang.String[] {
              "ProjectId", "Filter", "PageSize", "PageToken",
            });
    internal_static_google_datastore_admin_v1_ListIndexesResponse_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_datastore_admin_v1_ListIndexesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_ListIndexesResponse_descriptor,
            new java.lang.String[] {
              "Indexes", "NextPageToken",
            });
    internal_static_google_datastore_admin_v1_IndexOperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_datastore_admin_v1_IndexOperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_datastore_admin_v1_IndexOperationMetadata_descriptor,
            new java.lang.String[] {
              "Common", "ProgressEntities", "IndexId",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.datastore.admin.v1.IndexProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
