// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/datastore/admin/v1/migration.proto
// Protobuf Java Version: 4.33.0

package com.google.datastore.admin.v1;

@com.google.protobuf.Generated
public interface MigrationStateEventOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.datastore.admin.v1.MigrationStateEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The new state of the migration.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationState state = 1;</code>
   *
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();

  /**
   *
   *
   * <pre>
   * The new state of the migration.
   * </pre>
   *
   * <code>.google.datastore.admin.v1.MigrationState state = 1;</code>
   *
   * @return The state.
   */
  com.google.datastore.admin.v1.MigrationState getState();
}
